name: Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'

      - run: npm ci

      - run: npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - run: npm run release
