name: Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '24.10.0'

      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.1

      - run: pnpm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - run: pnpm run release
